name: weza
description: A Flutter app that fetches and categorizes M-Pesa SMS messages.
version: 1.0.0+1

environment:
  sdk:  ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.0.5
  
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  
  # SMS access
  flutter_sms_inbox: ^1.0.3
  permission_handler: ^11.0.1
  
  # UI
  cupertino_icons: ^1.0.5
  intl: ^0.17.0
  fl_chart: ^0.63.0
  sqflite: ^2.4.2
  mockito: ^5.4.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
  
  fonts:
    - family: Roboto
